#!/bin/bash

## if console font is unreadably small
# cd /usr/share/consolefonts/
# setfont Lat15-Terminus32x16.psf.gz

## to temporarily attach to wifi
# ip a
# wpa_passphrase <ssid> <pwd> > /etc/wpa_supplicant/wpa_supplicant.conf
# /sbin/wpa_supplicant -i<interface> -c/etc/wpa_supplicant/wpa_supplicant.conf -d &


[[ "$USER" = "root" ]] &&
    apt update &&
    apt upgrade -y && 
    apt install -y sudo &&
    adduser masse &&
    adduser masse sudo &&
    exit 0

unset  LANGUAGE
unset  LC_CTYPE
LANG="$(locale -a | grep -Ei "en.us.utf")"

# set up sudo
command -v sudo || su root -c "apt install -y sudo"
groups | grep -q sudo || su root -c "/sbin/adduser $USER sudo"

# install some sane stuff
sudo apt-get update &&
    sudo apt-get upgrade -y &&
    sudo apt-get install --autoremove -y \
         aspell-en aspell-sv automake \
         bind9-dnsutils g++ gdb git iputils-ping \
         jq lsof make mosh ncdu netcat-traditional \
         pandoc pass psmisc shellcheck socat strace sysstat \
         tcpdump texlive-latex-recommended tmux traceroute whois

# get my stuff
[ ! -e ~/.git ] &&
    (cd /tmp &&
         rm -rf dotfiles &&
         git clone https://github.com/massemanet/dotfiles.debian dotfiles &&
         cd dotfiles &&
         git remote set-url origin git@github.com:massemanet/dotfiles.debian &&
         mv .git ~ &&
         cd ~ &&
         git reset --hard)

# get the pet files
[ -d ~/pet ] || ~/bin/pet unpack

# install utilities
# command -v sway  || ~/bin/install.sh sway
# command -v emacs || ~/bin/install.sh emacs
command -v erl   || ~/bin/install.sh erlang
# command -v brave-browser || ~/bin/install.sh brave
# command -v chromium      || ~/bin/install.sh chromium
# command -v firefox       || ~/bin/install.sh firefox
# command -v keybase       || ~/bin/install.sh keybase
# command -v spotify       || ~/bin/install.sh spotify
# command -v aws-vault     || ~/bin/install.sh aws-vault
# command -v aws           || ~/bin/install.sh awscli
# command -v bazel         || (~/bin/install.sh bazel && ~/bin/install.sh bazelisk)
# command -v docker        || ~/bin/install.sh docker
# command -v kubectl       || ~/bin/install.sh kubectl
# command -v gimp          || ~/bin/install.sh gimp
# command -v wireshark     || ~/bin/install.sh wireshark

