#!/bin/bash

# to get this file;
# curl https://git.sr.ht/~massemanet/dotfiles/blob/server/INSTALL > ~/INSTALL

_err() {
    [ -n "$1" ] && echo "$1"
    exit 6
}

# C locale ftw
unset LC_CTYPE
unset LANGUAGE
LANG="$(locale -a | grep -Ei "c.utf" || echo "C")"

# sane path
export PATH=/usr/local/bin:/usr/bin:/usr/sbin

# do we have apt?
command -v apt-get || _err "no apt."

# we want sudo
if ! command -v sudo
then if [ "$USER" = "root" ]
     then apt-get install -y sudo
     else _err "no sudo."
     fi
fi
grep "sudo:" /etc/group || _err "no sudo group."

# add our user
AUSER=masse
ADDUSER=$(cat <<HERE
adduser "$AUSER" &&
adduser "$AUSER" sudo &&
mkdir "/home/$AUSER/.ssh" &&
cp .ssh/authorized_keys "/home/$AUSER/.ssh/" &&
chown -R "$AUSER:$AUSER" "/home/$AUSER"
HERE
       )

# we're either root, or an admin user who can do sudo.
if ! grep "$AUSER:" /etc/passwd
then if [ "$USER" = "root" ]
     then sh -c "$ADDUSER"
     else sudo sh -c "$ADDUSER"
     fi
fi

# install some sane stuff
sudo apt-get update &&
    sudo apt-get upgrade -y &&
    sudo apt-get install --autoremove -y \
         aspell-en aspell-sv automake \
         bind9-dnsutils \
         curl \
         deborphan \
         emacs-nox \
         g++ gdb git \
         jq \
         lksctp-tools lsof \
         make \
         ncdu netcat-traditional \
         pandoc python-is-python3 \
         shellcheck socat strace sysstat \
         tcpdump texinfo texlive-latex-recommended traceroute tree \
         unzip \
         whois

# get user stuff
if [ "$USER" = "$AUSER" ]; then
    cd ~ || _err "no ~$AUSER"
    # get dotfiles
    [ ! -e ~/.git ] &&
        cd /tmp &&
        rm -rf dotfiles &&
        git clone https://git.sr.ht/~massemanet/dotfiles dotfiles &&
        cd dotfiles &&
        mv .git ~ &&
        cd ~ &&
        git reset --hard &&
        git checkout server &&
        chmod 700 .gnupg &&
        echo "installed dotfiles"

    # init emacs
    command -v emacs &&
        EMACSDIR="$(eval readlink -f "$(2>&1 emacs --no-site-file --batch --eval "(message user-emacs-directory)")")" &&
        rm -rf ~/.emacs.d &&
        ln -s ~/.config/emacs ~/.emacs.d &&
        [ -f "$EMACSDIR/init.el" ] &&
        emacs --no-site-file --batch --eval "(require 'init \"$EMACSDIR/init.el\")" &&
        [ -d "$EMACSDIR/straight/repos/otp" ] &&
        [ ! -L "$EMACSDIR/straight/repos/otp" ] &&
        mkdir -p ~/git &&
        rm -rf ~/git/otp &&
        mv "$EMACSDIR/straight/repos/otp" ~/git &&
        ln -s ~/git/otp "$EMACSDIR/straight/repos" &&
        echo "installed emacs"
fi
