#!/bin/bash

## if console font is unreadably small
# cd /usr/share/consolefonts/
# setfont Lat15-Terminus32x16.psf.gz

## to temporarily attach to wifi
# ip a
# wpa_passphrase <ssid> <pwd> > /etc/wpa_supplicant/wpa_supplicant.conf
# /sbin/wpa_supplicant -i<interface> -c/etc/wpa_supplicant/wpa_supplicant.conf -d &

unset  LANGUAGE
unset  LC_CTYPE
LANG="$(locale -a | grep -Ei "en.us.utf")"

[[ "$USER" = "root" ]] &&
    apt update &&
    apt upgrade -y && 
    apt install -y sudo &&
    adduser masse &&
    adduser masse sudo &&
    exit 0

# set up sudo
command -v sudo || su root -c "apt install -y sudo"
groups | grep -q sudo || su root -c "/sbin/adduser $USER sudo"

# install some sane stuff
sudo apt-get update &&
    sudo apt-get upgrade -y &&
    sudo apt-get install --autoremove -y \
         aspell-en aspell-sv automake \
         bind9-dnsutils g++ gdb git iputils-ping \
         jq lsof make mosh ncdu netcat-traditional \
         pandoc pass psmisc shellcheck socat strace sysstat \
         tcpdump texlive-latex-recommended tmux traceroute whois

# get manèt stuff
[ ! -e ~/.git ] &&
    (cd /tmp &&
         rm -rf dotfiles &&
         git clone https://git.sr.ht/~massemanet/dotfiles dotfiles &&
         cd dotfiles &&
         git remote set-url origin git@git.sr.ht:~massemanet/dotfiles &&
         mv .git ~ &&
         cd ~ &&
         git checkout server
         git reset --hard)

[ ! -e ~/git/pet ] &&
    (cd ~/git &&
         git clone https://git.sr.ht/~massemanet/pet &&
         cd pet &&
         ./pet pull)

# install utilities
# command -v emacs || ~/bin/install.sh emacs
# command -v erl   || ~/bin/install.sh erlang
# command -v docker        || ~/bin/install.sh docker

